# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 373830a71972098f8974dc4501500c18af96ccc72abaf28e4780155728f42e58a43d34e5a686a701063fd395e20a79e4bb5425fd5b971ab6b98ec9bc2e563672

test:
  secret_key_base: e0fd8b84a045d0f21e6efac14f6e9e4ea6dc0e95a0d78c4858989bed01a9c11c9e2579cda3743c0817a4d9ebc9272fd77e4bcf81d2d38988c673bb39e8d342ee

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
